---
- hosts: '{{ target }}'
  become: true
  tasks:
  - name: update apt
    apt:
      update_cache=yes 
      force_apt_get=yes
      cache_valid_time=3600
  - name: install addons
    apt:
      name: '{{ item }}'
      update_cache: no
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  - name: install gpg
    shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg --y'
  - name: setup sources
    shell: 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
  - name: update apt
    apt:
      update_cache=yes
      force_apt_get=yes
      cache_valid_time=3600
  - name: install docker
    apt:
#      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      name: '{{ item }}'
      state: present
      update-cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
  - name: setup docker image directory
    shell: 'echo "{\n   \"data-root\": \"/docker/images\"\n}" > /etc/docker/daemon.json'
    when: dimage is defined
  - name: stop docker daemon
    service:
      name: docker
      state: stopped
  - name: start & enable docker
    service: 
      name: docker
      state: started
      enabled: yes
  - name: add ansible to docker group
    user: 
      name: ansible
      groups: docker
      append: yes
